<a href="https://colab.research.google.com/github/swaroopsaikuchi/Neural_Tensor/blob/main/tensorflow_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.13.0


In [ ]:
# create tensors with tf.constant()
scalar = tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions  )
scalar.ndim


0

In [ ]:
# creating a vector
vector = tf.constant([9,8,7])
vector


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([9, 8, 7], dtype=int32)>

In [ ]:
# creating a matrix
matrix = tf.constant([[10,7,7],
                      [7,8,9]])
matrix


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  7],
       [ 7,  8,  9]], dtype=int32)>

In [ ]:
# declaring the d type
another_matrix = tf.constant([[10.99,2,3],
                              [2,8,7],
                              [3,5,7],
                              [5,6,7]],dtype = tf.float64)
another_matrix

<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[10.99,  2.  ,  3.  ],
       [ 2.  ,  8.  ,  7.  ],
       [ 3.  ,  5.  ,  7.  ],
       [ 5.  ,  6.  ,  7.  ]])>

In [ ]:
#create a tensor
tensor = tf.constant([[[3,4,5],
                       [7,8,9]],
                      [[4,7,8],
                       [5,6,7]],
                      [[3,6,7],
                       [7,6,5]],
                      [[3,6,7],
                       [5,6,7]]])
tensor

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[3, 4, 5],
        [7, 8, 9]],

       [[4, 7, 8],
        [5, 6, 7]],

       [[3, 6, 7],
        [7, 6, 5]],

       [[3, 6, 7],
        [5, 6, 7]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
# now we try tf.variable()
import tensorflow as tf
changeable_tensor = tf.Variable([7,8])
unchangeable_tensor = tf.constant([8,8])
changeable_tensor[0].assign(4)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([4, 8], dtype=int32)>

#creating random tensors
#random tensors are tensors of some arbitary size which contain random
#....numbers


In [ ]:
#create two random (but the same) tensors
import tensorflow as tf
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.uniform(shape=(3,2))
random_2 = tf.random.Generator.from_seed(8)
random_2 = random_2.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

In [ ]:
# shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesnt effect learning )
not_shuffled = tf.constant([[10,7,],
                            [3,4],
                            [2,5]])
#shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 2,  5]], dtype=int32)>

it looks like we want our shuffled tensors to be in the same order , we have got to use the global level random seed .


In [ ]:
import tensorflow as tf
tf.random.set_seed(42)
not_shuffled = tf.constant([[10,7,],
                            [3,4],
                            [2,5]])
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

other ways to create tensors

In [ ]:
# create tensors all ones
import tensorflow as tf
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create tensors with all zeros
tf.zeros([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

the main diff between numpy arrays and tensorflow arrays is that the tensors can be rum much faster in GPU

In [ ]:
import numpy as np
import tensorflow as tf
# X = tf.constant(matrix) #capital for matrix
# y = tf.constant(vector) #small letter for vector
numpy_A = np.arange(1,25,dtype=np.int32)
A = tf.constant(numpy_A,shape = (2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

getting information from tensorsw

important terms
* shape -- tensor.shape
* rank  -- tensor.ndim
* axis or dimension -- tensor[0]
* size  -- tf.size()

In [ ]:
# creating a rank 4 tensor
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

In [ ]:
rank_4_tensor.shape[-1]

5

Indexing tensors
tensors can be indexed just like python list

In [ ]:
# in python lists
list = [1,2,3,4]
list[:3]

[1, 2, 3]

In [ ]:
# get the first 2 elements of each dimenion
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# create a rank 2 tensor(2 dimensions )
rank_2_tensor = tf.constant([[1,2],
                             [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
# getting the last item of each of row of our  rank 2 tensor
rank_2_tensor[:, -1 ]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
# add extra dimension for rank 2 tensor
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# alternatives for tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) # -1 means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# manipulating tensors (tensor operation)
# basic operations
# '+',"-","*","%"
tensor = tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# we can use the tensor flow built in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Matrix Multiplication

In [ ]:
# matrix multiplication in tensor flow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor * tensor # both are different

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
 tensor @ tensor # matrix multiplication in python

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
X = tf.constant([[2,3,4],
                 [3,4,5],
                 [6,7,8]])

Y = tf.constant([[7,8],
                 [10,11],
                 [2,5]])
#X , Y
#tf.matmul(X,Y)
# used for reshape a matrix
tf.reshape(Y,shape=(2,3))
X

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
# can do the same with transpose
tf.transpose(X)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 6],
       [3, 4, 7],
       [4, 5, 8]], dtype=int32)>

you can perform matrix multiplication sing :
* tf.matmul(x,Y)
* tf.tensordot()


In [ ]:
# perform dot product on x and y
tf.tensordot(tf.transpose(X),Y,axes = 1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 56,  79],
       [ 75, 103],
       [ 94, 127]], dtype=int32)>

In [ ]:
# perform matricx multiplication between x and y (reshaped)
tf.reshape(Y,shape=(2,3))
tf.tensordot(X,Y,axes = 1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 52,  69],
       [ 71,  93],
       [128, 165]], dtype=int32)>

In [ ]:
# changing the datatype in the tensor
B = tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C  = tf.constant([1,2,3])
C.dtype


tf.int32

In [ ]:
#changing datatype float32 to int32
B = tf.cast(B,dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
D = tf.cast(C,dtype=tf.float16)
D

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1., 2., 3.], dtype=float16)>

In [ ]:
# aggregating tensors
# condensing them from multiple values down to a smaller amount of values
# get the absolute value
D = tf.constant([-7,-10])
D


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# lets go through the following forms of aggregation
#get the min
#get the max
#get the mean of a tensor
#get the sum of a tensor

In [ ]:
# create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([32, 19, 12, 18,  9, 76, 76, 64, 77, 17, 32, 23, 21, 51,  7, 15, 94,
        5, 49, 81, 69, 38,  0, 65, 43, 54, 34, 97, 69, 50, 89, 14, 55, 97,
       28, 88, 93, 96, 57, 17, 10, 93, 46, 56, 93, 57, 79, 44, 41, 80])>

In [ ]:
E.ndim , tf.size(E) , E.shape

(1, <tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]))

In [ ]:
# find the min
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
# find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [ ]:
# find the sum of a tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2530>

In [ ]:
# find the positional maximum and minimum
# create new tensor for finding pos max and min
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find the pos maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# index on our largest value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
 F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# find the positional min
tf.argmin(F)
# indexing
F[tf.argmin(F)]
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# create a tensor to get started
# squeeze concept
# basically remove all ones in the shape (reduce the dimensions )
G = tf.constant((tf.random.uniform(shape=[50])),shape=(1,1,1,1,50))

In [ ]:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

One - Hot Encoding

In [ ]:
# create a list of indices
some_list = [0,1,2,4]
# one - hot encoding of our list
tf.one_hot(some_list , depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(some_list,depth=5,on_value = "hii", off_value= "bye")

<tf.Tensor: shape=(4, 5), dtype=string, numpy=
array([[b'hii', b'bye', b'bye', b'bye', b'bye'],
       [b'bye', b'hii', b'bye', b'bye', b'bye'],
       [b'bye', b'bye', b'hii', b'bye', b'bye'],
       [b'bye', b'bye', b'bye', b'bye', b'hii']], dtype=object)>

In [ ]:
### squaring , log , square root
H = tf.range(1,10)
H


<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# find the log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
# tensors and numpy
#Tensorflow interacts with numpy arrays
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
np.array(J) , type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
L = tf.constant([3.])
np.array(L)

array([3.], dtype=float32)